/**
 * Emit `generated/` from the endpoint table in `typert-endpoints.mjs`.
 *
 * Two faces come out, in the exact formats the harness's own generator produces:
 *
 * - `typert.host.js` exports `TYPERT`, the Host manifest `@deepseek-ai/dsh-typert-loader`
 *   validates and registers.
 * - `typert.remote-client.js` exports `TYPERT_REMOTE`, the descriptor set the browser half hands to
 *   `ctx.remote.$mount()`.
 *
 * Both are standalone modules importing only `zod`, because the Web Client loads the client face
 * without this package's build ever running.
 */
import { createHash } from 'node:crypto'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import { ENDPOINTS, PACKAGE, SERVICE, SOURCE_FILE } from './typert-endpoints.mjs'
import { FINGERPRINT_FILE, fingerprint } from './typert-fingerprint.mjs'

const ROOT = fileURLToPath(new URL('..', import.meta.url))

/** Header both faces carry, naming what produced them. */
const HEADER = `/* Generated by scripts/build-typert.mjs from scripts/typert-endpoints.mjs — do not edit. */\nimport { z } from 'zod'\n`

/**
 * The constant name one endpoint's parameter or result schema is bound to.
 *
 * Mirrors the harness generator's naming so a hand comparison between this artifact and one it
 * produced reads as the same document.
 * @param method - the endpoint's method name.
 * @param suffix - `result`, or `parameter_<n>`.
 * @returns the identifier.
 */
function constantName(method, suffix) {
  const owner = `${PACKAGE}_${SERVICE}_${method}`.replace(/[^A-Za-z0-9]+/g, '_')
  return `_${owner}_${suffix}$schema`
}

/**
 * Render every endpoint's schema constants.
 * @returns the declarations, one per line group.
 */
function renderSchemas() {
  const lines = []
  for (const endpoint of ENDPOINTS) {
    endpoint.parameters.forEach((parameter, index) => {
      lines.push(`const ${constantName(endpoint.method, `parameter_${index}`)} = ${parameter.schema}`)
    })
    lines.push(`const ${constantName(endpoint.method, 'result')} = ${endpoint.result.schema}`)
  }
  return lines.join('\n')
}

/**
 * Render one endpoint as an `InvocationDescriptor` literal.
 * @param endpoint - the endpoint to render.
 * @returns the literal's source text, indented for an array element.
 */
function renderDescriptor(endpoint) {
  const parameters = endpoint.parameters.map((parameter, index) => `        {
          name: '${parameter.name}',
          wire: '${parameter.name}',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '../src/host/types.ts#${parameter.typeSymbol}',
            schema: ${constantName(endpoint.method, `parameter_${index}`)},
          },
        },`).join('\n')
  return `    {
      id: '${PACKAGE}#${SERVICE}/${endpoint.method}',
      service: '${SERVICE}',
      namespace: '${SERVICE}',
      method: '${endpoint.method}',
      invocation: { kind: 'direct' },
      parameters: [
${parameters}
      ],
${endpoint.cancellation === true ? "      cancellation: { parameter: 'signal' },\n" : ''}      result: {
        mode: 'strict',
        typeSymbol: '../src/host/types.ts#${endpoint.result.typeSymbol}',
        schema: ${constantName(endpoint.method, 'result')},
      },
      sourceLocation: {"file":"${SOURCE_FILE}","line":${endpoint.line},"column":3},
    },`
}

/**
 * Read the JSDoc summary the Host declares for one endpoint, so the manifest's documentation is the
 * source's rather than a second description that can contradict it.
 * @param source - the text of `src/host/index.ts`.
 * @param method - the endpoint's method name.
 * @returns the first sentence of the method's JSDoc, or a stable fallback.
 */
function summaryFor(source, method) {
  const at = source.indexOf(`  @Remote('${method}')`)
  if (at < 0) return `The ${method} endpoint.`
  const before = source.slice(0, at)
  const open = before.lastIndexOf('  /**')
  if (open < 0) return `The ${method} endpoint.`
  const block = before.slice(open)
  const first = block.split('\n').slice(1).map(line => line.replace(/^\s*\*ic?\s?/, '').replace(/^\s*\*\s?/, '').trim())
    .find(line => line.length > 0 && !line.startsWith('@'))
  return first ?? `The ${method} endpoint.`
}

/**
 * Render the FaceModel the loader validates: one service, its members, and no events or objects.
 * @param source - the text of `src/host/index.ts`.
 * @returns the model literal's source text.
 */
function renderModel(source) {
  const members = ENDPOINTS.map(endpoint => ({
    kind: 'method',
    name: endpoint.method,
    signature: `@Remote('${endpoint.method}') async ${endpoint.method}(request: ${endpoint.parameters[0].typeSymbol}${endpoint.cancellation === true ? ', signal: AbortSignal' : ''}): Promise<${endpoint.result.typeSymbol}>`,
    summary: summaryFor(source, endpoint.method),
  }))
  const model = {
    services: [{
      description: 'Host-side memory endpoint, settings owner, and harness-hook consumer.',
      summary: 'Host-side memory endpoint, settings owner, and harness-hook consumer.',
      tags: [],
      jsDoc: '/** Host-side memory endpoint, settings owner, and harness-hook consumer. */',
      key: SERVICE,
      exportName: 'MemoryService',
      members,
      types: [],
    }],
    events: [],
    objects: [],
  }
  return JSON.stringify(model, null, 4).replace(/\n/g, '\n  ')
}

const hostSource = await readFile(new URL(SOURCE_FILE, `file://${ROOT}`), 'utf8')
const schemas = renderSchemas()
const descriptors = ENDPOINTS.map(renderDescriptor).join('\n')

const host = `${HEADER}
${schemas}

export const TYPERT = {
  package: '${PACKAGE}',
  face: 'host',
  schemas: [
  ],
  invocations: [
${descriptors}
  ],
  model: ${renderModel(hostSource)},
}

export default TYPERT
`

const remote = `${HEADER}
${schemas}

export const TYPERT_REMOTE = {
  package: '${PACKAGE}',
  descriptors: [
${descriptors}
  ],
}

export default TYPERT_REMOTE
`

/**
 * Render the Client's typed namespace declaration.
 *
 * The runtime reaches an endpoint as `ctx.remote.memory.search(...)`, and that property exists only
 * because a generated declaration merges it into `TypertRemoteNamespaceMap`. The namespace interface
 * is named by the hex of the namespace string — the harness generator's own convention, kept here so
 * two packages declaring the same namespace collide loudly instead of silently shadowing.
 * @returns the declaration module's source text.
 */
function renderRemoteDeclaration() {
  const hex = [...SERVICE].map(character => character.charCodeAt(0).toString(16).padStart(2, '0')).join('')
  const iface = `TypertRemoteNamespace$${hex}`
  const types = [...new Set(ENDPOINTS.flatMap(endpoint =>
    [...endpoint.parameters.map(parameter => parameter.typeSymbol), endpoint.result.typeSymbol]))].sort()
  const signature = endpoint => `(${endpoint.parameters
    .map(parameter => `${parameter.name}: ${parameter.typeSymbol}`)
    .join(', ')}${endpoint.cancellation === true ? ', signal?: AbortSignal' : ''}) => Promise<RemoteResult<${endpoint.result.typeSymbol}>>`
  return `/* Generated by scripts/build-typert.mjs — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { ${types.join(', ')} } from '../src/host/types.ts'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface ${iface} {
${ENDPOINTS.map(endpoint => `    ${endpoint.method}: ${signature(endpoint)}`).join('\n')}
  }
  interface TypertRemoteMap {
${ENDPOINTS.map(endpoint => `    '${SERVICE}/${endpoint.method}': ${signature(endpoint)}`).join('\n')}
  }
  interface TypertRemoteNamespaceMap {
    '${SERVICE}': ${iface}
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
`
}

await mkdir(new URL('generated/', `file://${ROOT}`), { recursive: true })
await writeFile(new URL('generated/typert.host.js', `file://${ROOT}`), host)
await writeFile(
  new URL('generated/typert.host.d.ts', `file://${ROOT}`),
  '/* Generated by scripts/build-typert.mjs — do not edit. */\n\nexport declare const TYPERT: unknown\nexport default TYPERT\n',
)
await writeFile(new URL('generated/typert.remote-client.js', `file://${ROOT}`), remote)
await writeFile(new URL('generated/typert.remote-client.d.ts', `file://${ROOT}`), renderRemoteDeclaration())
await writeFile(new URL(FINGERPRINT_FILE, `file://${ROOT}`), `${await fingerprint()}\n`)

const hash = createHash('sha256').update(host).digest('hex').slice(0, 12)
console.log(`typert: emitted ${ENDPOINTS.length} endpoint(s) (${hash})`)
